// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Enrico Weigelt, metux IT consult
//
// Package models implements the 'models sync' subcommand that updates
// the models.yaml file from opencode's model catalog.
//
// The sync preserves hand-edited fields (fallback chains, notes) from
// existing entries and marks removed models as disabled instead of
// deleting them — nothing is lost on rescan.
package models

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// --- opencode models --verbose JSON structure ---

type modelOutput struct {
	ID           string `json:"id"`
	ProviderID   string `json:"providerID"`
	Name         string `json:"name"`
	Capabilities struct {
		Temperature bool `json:"temperature"`
		Reasoning   bool `json:"reasoning"`
		Attachment  bool `json:"attachment"`
		Toolcall    bool `json:"toolcall"`
		Input       struct {
			Text  bool `json:"text"`
			Audio bool `json:"audio"`
			Image bool `json:"image"`
			Video bool `json:"video"`
			PDF   bool `json:"pdf"`
		} `json:"input"`
		Output struct {
			Text  bool `json:"text"`
			Audio bool `json:"audio"`
			Image bool `json:"image"`
			Video bool `json:"video"`
			PDF   bool `json:"pdf"`
		} `json:"output"`
	} `json:"capabilities"`
	Limit struct {
		Context int `json:"context"`
	} `json:"limit"`
}

// --- YAML file structure (models.yaml) ---

// yamlModel represents a single model entry in models.yaml.
// Hand-edited fields (Fallback, Note, Disabled) survive rescan.
type yamlModel struct {
	ID       string   `yaml:"id"`
	Provider string   `yaml:"provider"`
	Label    string   `yaml:"label"`
	Context  int      `yaml:"context"`
	Caps     []string `yaml:"caps,omitempty"`

	// Hand-edited fields — preserved across sync, never overwritten.
	Fallback string `yaml:"fallback,omitempty"`
	Note     string `yaml:"note,omitempty"`
	Disabled bool   `yaml:"disabled,omitempty"`
}

type yamlFile struct {
	Models []yamlModel `yaml:"models"`
}

// --- scanned model from opencode (before merge) ---

type scannedModel struct {
	id       string
	provider string
	label    string
	context  int
	caps     []string
}

// Models holds one invocation's resolved locations.
type Models struct {
	Root string
}

func New(root string) *Models { return &Models{Root: root} }

func (m *Models) modelsFilePath() string {
	return filepath.Join(m.Root, ".starfleet-ai", "conf", "models.yaml")
}

// Run is the entry point for the 'models' subcommand.
func (m *Models) Run(args []string) error {
	if len(args) < 1 {
		return m.printHelp()
	}
	switch args[0] {
	case "sync":
		return m.DoSync()
	case "--help", "-h":
		return m.printHelp()
	default:
		return fmt.Errorf("models: unknown subcommand: %s", args[0])
	}
}

func (m *Models) printHelp() error {
	fmt.Fprintln(os.Stderr, `Usage: starfleetctl models sync

Sync models.yaml from opencode's model catalog.

Behaviour:
  • New models in the catalog are added to the YAML.
  • Models present in the YAML but gone from the catalog are marked
    disabled: true (not deleted).
  • Hand-edited fields (fallback, note) on existing entries are preserved.
  • Capability tags (caps) are refreshed from the live catalog.
  • The file is only rewritten if something actually changed (idempotent).`)
	return nil
}

// DoSync runs the full scan → merge → write cycle.
func (m *Models) DoSync() error {
	outputPath := m.modelsFilePath()

	// 1. Scan live catalog.
	cmd := exec.Command("opencode", "models", "--verbose")
	cmd.Stderr = nil
	raw, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("models sync: opencode models --verbose failed: %w", err)
	}
	scanned, err := parseScanOutput(string(raw))
	if err != nil {
		return fmt.Errorf("models sync: %w", err)
	}

	// Build lookup: id → scanned.
	scanMap := make(map[string]scannedModel, len(scanned))
	for _, s := range scanned {
		scanMap[s.id] = s
	}

	// 2. Read existing YAML (if any) to preserve hand-edited fields.
	existing := m.readExistingYAML(outputPath)
	existMap := make(map[string]yamlModel, len(existing.Models))
	for _, e := range existing.Models {
		existMap[e.ID] = e
	}

	// 3. Merge.
	merged := m.merge(existMap, scanMap, scanned)

	// 4. Generate YAML.
	yamlBytes, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("models sync: yaml marshal: %w", err)
	}

	// Add header comment.
	var out strings.Builder
	out.WriteString("# Auto-generated by models sync — do not hand-edit the auto fields.\n")
	out.WriteString("# Regenerate: starfleetctl models sync\n")
	out.WriteString("# Source: opencode models --verbose\n")
	out.WriteString("#\n")
	out.WriteString("# Hand-edited fields that survive rescan: fallback, note, disabled.\n")
	out.WriteString("#\n")
	out.WriteString("# Fallback chain example — when model X is unavailable (quota, outage),\n")
	out.WriteString("# the system falls back to Y:\n")
	out.WriteString("#   - id: \"opencode/big-pickle\"\n")
	out.WriteString("#     fallback: \"nvidia/deepseek-ai/deepseek-v4-flash\"\n")
	out.WriteString("#\n")
	out.WriteString("---\n")
	out.Write(yamlBytes)

	content := out.String()

	// 5. Compare with existing file and only write if changed.
	existingContent, err := os.ReadFile(outputPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("models sync: read: %w", err)
	}
	if string(existingContent) == content {
		fmt.Printf("models sync: no changes (%d active, %d disabled)\n",
			countActive(merged.Models), countDisabled(merged.Models))
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("models sync: mkdir: %w", err)
	}
	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("models sync: write: %w", err)
	}

	fmt.Printf("models sync: updated %s (%d active, %d disabled)\n",
		outputPath, countActive(merged.Models), countDisabled(merged.Models))
	return nil
}

// readExistingYAML parses an existing models.yaml, returning an empty
// list if the file doesn't exist.
func (m *Models) readExistingYAML(path string) yamlFile {
	data, err := os.ReadFile(path)
	if err != nil {
		return yamlFile{}
	}
	// Strip the YAML header comments (lines starting with # or ---)
	// before parsing so yaml.v3 doesn't choke on our free-form header.
	lines := strings.Split(string(data), "\n")
	var clean []string
	started := false
	for _, l := range lines {
		if !started {
			if strings.HasPrefix(l, "---") {
				started = true
				clean = append(clean, l)
			} else if strings.HasPrefix(l, "#") || strings.TrimSpace(l) == "" {
				continue
			} else {
				started = true
				clean = append(clean, l)
			}
			continue
		}
		clean = append(clean, l)
	}

	var f yamlFile
	if err := yaml.Unmarshal([]byte(strings.Join(clean, "\n")), &f); err != nil {
		return yamlFile{}
	}
	return f
}

// merge produces the final YAML model list by combining existing entries
// (with hand-edited fields preserved) and freshly scanned entries.
func (m *Models) merge(existMap map[string]yamlModel, scanMap map[string]scannedModel, scanOrder []scannedModel) yamlFile {
	var out []yamlModel
	seen := make(map[string]bool)

	// Active models — in scan order (provider-sorted).
	for _, s := range scanOrder {
		seen[s.id] = true
		entry := yamlModel{
			ID:       s.id,
			Provider: s.provider,
			Label:    s.label,
			Context:  s.context,
			Caps:     s.caps,
		}
		// Preserve hand-edited fields from existing entry.
		if old, ok := existMap[s.id]; ok {
			entry.Fallback = old.Fallback
			entry.Note = old.Note
			// Only carry over disabled if explicitly set (re-enable on rescan
			// if model is back in catalog — disabled is only for absent models).
			entry.Disabled = false
		}
		out = append(out, entry)
	}

	// Disabled models — in existing YAML but gone from catalog.
	for id, old := range existMap {
		if seen[id] {
			continue
		}
		// Skip already-disabled entries that were disabled before this scan
		// AND have no fallback chain pointing to them (keep disabled state).
		out = append(out, yamlModel{
			ID:       old.ID,
			Provider: old.Provider,
			Label:    old.Label,
			Context:  old.Context,
			Caps:     old.Caps,
			Fallback: old.Fallback,
			Note:     old.Note,
			Disabled: true,
		})
	}

	// Sort: active first (by provider, label), then disabled.
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Disabled != out[j].Disabled {
			return !out[i].Disabled // active before disabled
		}
		if out[i].Provider != out[j].Provider {
			return out[i].Provider < out[j].Provider
		}
		return out[i].Label < out[j].Label
	})

	return yamlFile{Models: out}
}

func countActive(m []yamlModel) int {
	n := 0
	for _, v := range m {
		if !v.Disabled {
			n++
		}
	}
	return n
}

func countDisabled(m []yamlModel) int {
	n := 0
	for _, v := range m {
		if v.Disabled {
			n++
		}
	}
	return n
}

// --- opencode output parsing ---

func parseScanOutput(output string) ([]scannedModel, error) {
	lines := strings.Split(output, "\n")

	type modelLine struct {
		index int
		id    string
	}
	var modelIDs []modelLine
	for i, line := range lines {
		s := strings.TrimSpace(line)
		if s == "" || strings.HasPrefix(s, "{") || strings.HasPrefix(s, "}") || strings.HasPrefix(s, "\"") {
			continue
		}
		modelIDs = append(modelIDs, modelLine{i, s})
	}

	var models []scannedModel
	for idx, ml := range modelIDs {
		nextLine := len(lines)
		if idx+1 < len(modelIDs) {
			nextLine = modelIDs[idx+1].index
		}

		var jsonLines []string
		for j := ml.index + 1; j < nextLine; j++ {
			if strings.HasPrefix(strings.TrimSpace(lines[j]), "{") {
				jsonLines = lines[j:nextLine]
				break
			}
		}
		if len(jsonLines) == 0 {
			continue
		}

		jsonStr := strings.Join(jsonLines, "\n")
		var data modelOutput
		if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
			fixed := regexp.MustCompile(`,\s*}`).ReplaceAllString(jsonStr, "}")
			fixed = regexp.MustCompile(`,\s*]`).ReplaceAllString(fixed, "]")
			if err2 := json.Unmarshal([]byte(fixed), &data); err2 != nil {
				continue
			}
		}

		if !data.Capabilities.Toolcall || data.Limit.Context <= 0 {
			continue
		}

		models = append(models, scannedModel{
			id:       fmt.Sprintf("%s/%s", data.ProviderID, data.ID),
			provider: data.ProviderID,
			label:    data.Name,
			context:  data.Limit.Context,
			caps:     extractCaps(&data),
		})
	}

	sort.Slice(models, func(i, j int) bool {
		if models[i].provider != models[j].provider {
			return models[i].provider < models[j].provider
		}
		return models[i].label < models[j].label
	})
	return models, nil
}

func extractCaps(d *modelOutput) []string {
	var caps []string
	if d.Capabilities.Reasoning {
		caps = append(caps, "reasoning")
	}
	if d.Capabilities.Attachment {
		caps = append(caps, "attachment")
	}
	if d.Capabilities.Input.Image {
		caps = append(caps, "image-in")
	}
	if d.Capabilities.Output.Image {
		caps = append(caps, "image-out")
	}
	if d.Capabilities.Input.Audio {
		caps = append(caps, "audio-in")
	}
	if d.Capabilities.Output.Audio {
		caps = append(caps, "audio-out")
	}
	if d.Capabilities.Input.Video {
		caps = append(caps, "video-in")
	}
	if d.Capabilities.Output.Video {
		caps = append(caps, "video-out")
	}
	if d.Capabilities.Input.PDF {
		caps = append(caps, "pdf-in")
	}
	if d.Capabilities.Output.PDF {
		caps = append(caps, "pdf-out")
	}
	return caps
}
