// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Enrico Weigelt, metux IT consult
//
// Go port of scripts/pr-comment: post a PR comment from a file, with an
// optional --bot-review banner prepend (AGENTS.md's "Automated reviews"
// mandated wording, so it can't drift between call sites).
package ghpr

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/metux/starfleetctl/internal/identity"
)

const prCommentUsage = `usage: starfleetctl pr-comment <pr#> <body-file> [--bot-review]
env: STARFLEET_GITHUB_REPO   repo slug (or $REPO for backward compat)
     STARFLEET_SHIP_ID       ship name shown in the --bot-review banner (falls back to user@host)
`

// RunPRComment implements `starfleetctl pr-comment`.
func RunPRComment(args []string) int {
	if len(args) >= 1 && (args[0] == "-h" || args[0] == "--help") {
		fmt.Print(prCommentUsage)
		return 0
	}
	if len(args) < 2 {
		fmt.Fprint(os.Stderr, prCommentUsage)
		return 2
	}

	pr := strings.TrimPrefix(args[0], "#")
	file := args[1]
	botReview := len(args) >= 3 && args[2] == "--bot-review"

	if _, err := os.Stat(file); err != nil {
		fmt.Fprintf(os.Stderr, "pr-comment: no such file: %s\n", file)
		return 1
	}

	if botReview {
		body, err := os.ReadFile(file)
		if err != nil {
			fmt.Fprintln(os.Stderr, "pr-comment:", err)
			return 1
		}
		ship := shipName()
		banner := fmt.Sprintf("> \U0001F916 **Automated review** — generated by Claude Code (ship: %s) on behalf of @metux. Not a human review.\n\n", ship)

		tmp, err := os.CreateTemp("", "pr-comment-*.md")
		if err != nil {
			fmt.Fprintln(os.Stderr, "pr-comment:", err)
			return 1
		}
		defer os.Remove(tmp.Name())
		if _, err := tmp.WriteString(banner); err != nil {
			tmp.Close()
			fmt.Fprintln(os.Stderr, "pr-comment:", err)
			return 1
		}
		if _, err := tmp.Write(body); err != nil {
			tmp.Close()
			fmt.Fprintln(os.Stderr, "pr-comment:", err)
			return 1
		}
		tmp.Close()
		file = tmp.Name()
	}

	cmd := exec.Command("gh", "pr", "comment", pr, "--repo", repo(), "--body-file", file)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fprintErr("pr-comment", err)
		return 1
	}
	return 0
}

// shipName mirrors the bash originals' `${STARFLEET_SHIP_ID:-$(id -un)@$(hostname -s ...)}`
// fallback used in the --bot-review banner.
func shipName() string {
	if v := identity.ShipID(); v != "" {
		return v
	}
	user := os.Getenv("USER")
	if user == "" {
		user = "user"
	}
	host, err := os.Hostname()
	if err != nil || host == "" {
		host = "host"
	}
	if i := strings.IndexByte(host, '.'); i >= 0 {
		host = host[:i]
	}
	return user + "@" + host
}
