// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Enrico Weigelt, metux IT consult
//
// Package agents implements the modular AGENTS.md system: the root
// AGENTS.md file is fixed forever (a short notice plus one `@agents.d/
// index.md` import), and the actual content lives in per-topic fragment
// files under agents.d/, each a Markdown body with a small frontmatter
// block — same shape and rationale as internal/dashboard's theme system
// (DASHBOARD.md restructuring, directive m0048/m0073): concurrent ships
// editing different fragments touch different files, and only `reindex`
// (a pure function of the current fragment set) touches the generated
// agents.d/index.md.
//
// This only works because Claude Code resolves `@file` imports
// recursively up to 4 hops (verified against the official docs before
// building this): CLAUDE.md -> AGENTS.md -> agents.d/index.md ->
// agents.d/<slug>.md is 3 hops, comfortably within that limit.
package agents

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Agents holds one invocation's resolved locations.
type Agents struct {
	Root   string // workspace root (toplevel of the git checkout)
	GitDir string // absolute .git dir, for the shared clone lock file
	File   string // absolute path to the root AGENTS.md
}

// New resolves an Agents rooted at the given workspace root.
func New(root string) (*Agents, error) {
	out, err := runCapture(root, "git", "rev-parse", "--absolute-git-dir")
	if err != nil {
		return nil, fmt.Errorf("agents: not inside a git working tree: %w", err)
	}
	return &Agents{
		Root:   root,
		GitDir: strings.TrimSpace(out),
		File:   filepath.Join(root, "AGENTS.md"),
	}, nil
}

func (a *Agents) branch() (string, error) {
	out, err := runCapture(a.Root, "git", "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(out), nil
}

func (a *Agents) FragmentsDir() string {
	return filepath.Join(a.Root, "agents.d")
}

func (a *Agents) IndexFile() string {
	return filepath.Join(a.FragmentsDir(), "index.md")
}

func (a *Agents) fragmentPath(slug string) string {
	return filepath.Join(a.FragmentsDir(), slug+".md")
}

// rootNotice is the ENTIRE fixed content of the root AGENTS.md — this
// package never writes anything else there. Deliberately short: its only
// job is the one import line that pulls in everything else.
const rootNotice = `# AGENTS.md

This file intentionally never changes beyond this notice — it only imports
the current fragment index. Add or edit content in ` + "`agents.d/<slug>.md`" + `
instead (see ` + "`.bin/starfleetctl agents`" + ` — list/show/write/new/reindex/commit),
not here. ` + "`agents.d/index.md`" + ` (below) is auto-regenerated by ` + "`agents reindex`" + `
and lists every current fragment in order; do not hand-edit it either.

@agents.d/index.md
`

const indexHeader = `<!-- Auto-generated by ` + "`.bin/starfleetctl agents reindex`" + ` — do not hand-edit.
     Edit the fragment files themselves (agents.d/<slug>.md) instead, then
     re-run reindex (agents new/write do this for you automatically). -->

`
