// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Enrico Weigelt, metux IT consult
//
// Package agents implements the modular CLAUDE.md system: the root
// CLAUDE.md file is fixed forever (a short notice plus one `@agents.d/
// index.md` import), and the actual content lives in per-topic fragment
// files under agents.d/, each a Markdown body with a small frontmatter
// block — same shape and rationale as internal/dashboard's theme system
// (DASHBOARD.md restructuring, directive m0048/m0073): concurrent ships
// editing different fragments touch different files, and only `reindex`
// (a pure function of the current fragment set) touches the generated
// agents.d/index.md.
//
// This only works because Claude Code resolves `@file` imports
// recursively up to 4 hops (verified against the official docs before
// building this): CLAUDE.md -> agents.d/index.md ->
// agents.d/<slug>.md is 2 hops, comfortably within that limit.
//
// Some agents (notably opencode) do not resolve `@`-imports, so `reindex`
// also supports an inline mode: with the .starfleet-ai/agents-inline marker
// present (or `reindex --inline`), it writes a single self-contained
// CLAUDE.md — the fixed root notice followed by every fragment's body — with
// no `@` at all. `agents reindex` (and `new`/`write`, which reindex) honor the
// marker, so a workspace keeps its chosen mode.
package agents

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Agents holds one invocation's resolved locations.
type Agents struct {
	Root   string // workspace root (toplevel of the git checkout)
	GitDir string // absolute .git dir, for the shared clone lock file
	File   string // absolute path to the root CLAUDE.md
}

// New resolves an Agents rooted at the given workspace root.
func New(root string) (*Agents, error) {
	out, err := runCapture(root, "git", "rev-parse", "--absolute-git-dir")
	if err != nil {
		return nil, fmt.Errorf("agents: not inside a git working tree: %w", err)
	}
	return &Agents{
		Root:   root,
		GitDir: strings.TrimSpace(out),
		File:   filepath.Join(root, "CLAUDE.md"),
	}, nil
}

func (a *Agents) branch() (string, error) {
	out, err := runCapture(a.Root, "git", "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(out), nil
}

// FragmentsDir returns the path to user-maintained fragments (agents.d/).
func (a *Agents) FragmentsDir() string {
	return filepath.Join(a.Root, "agents.d")
}

// StarfleetFragmentsDir returns the path to auto-rolled starfleet fragments
// (.starfleet-ai/agents.d/starfleet/). These are tool-owned and gitignored.
func (a *Agents) StarfleetFragmentsDir() string {
	return filepath.Join(a.Root, ".starfleet-ai", "agents.d", "starfleet")
}

// IndexFile returns the path to the auto-generated fragment index
// (.starfleet-ai/agents.d/index.md).
func (a *Agents) IndexFile() string {
	return filepath.Join(a.Root, ".starfleet-ai", "agents.d", "index.md")
}

func (a *Agents) fragmentPath(slug string) string {
	// Starfleet-owned fragments live under .starfleet-ai/agents.d/starfleet/
	if strings.HasPrefix(slug, "starfleet/") {
		return filepath.Join(a.Root, ".starfleet-ai", "agents.d", slug+".md")
	}
	return filepath.Join(a.FragmentsDir(), slug+".md")
}

// fragmentImportPath returns the @-import path for a fragment in index.md.
// Starfleet fragments use .starfleet-ai/agents.d/, user fragments use agents.d/.
func (a *Agents) fragmentImportPath(m FragmentMeta) string {
	if m.IsStarfleet {
		return ".starfleet-ai/agents.d/" + m.Slug + ".md"
	}
	return "agents.d/" + m.Slug + ".md"
}

// rootNotice is the ENTIRE fixed content of the root CLAUDE.md — this
// package never writes anything else there. Deliberately short: its only
// job is the one import line that pulls in everything else.
const rootNotice = `# CLAUDE.md

This file intentionally never changes beyond this notice — it only imports
the current fragment index. Add or edit content in ` + "`.starfleet-ai/agents.d/<slug>.md`" + `
instead (see ` + "`.starfleet-ai/bin/starfleetctl agents`" + ` — list/show/write/new/reindex/commit),
not here. ` + "`.starfleet-ai/agents.d/index.md`" + ` (below) is auto-regenerated by ` + "`agents reindex`" + `
and lists every current fragment in order; do not hand-edit it either.

@.starfleet-ai/agents.d/index.md
`

// starfleetPointer is the single import line that links CLAUDE.md to the
// fragment index. Inserted into existing user-written CLAUDE.md files that
// lack it — never overwrites existing content.
const starfleetPointer = "\n@.starfleet-ai/agents.d/index.md\n"

// hasStarfleetPointer reports whether data already contains the starfleet
// fragment import pointer.
func hasStarfleetPointer(data []byte) bool {
	return strings.Contains(string(data), "@.starfleet-ai/agents.d/index.md")
}

// appendGitignoreEntry appends entry to the given .gitignore file if not
// already present. Creates the file if it doesn't exist.
func appendGitignorePath(root, entry string) error {
	gi := filepath.Join(root, ".gitignore")
	data, err := os.ReadFile(gi)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if os.IsNotExist(err) {
		return os.WriteFile(gi, []byte(entry+"\n"), 0o644)
	}
	if strings.Contains(string(data), entry) {
		return nil
	}
	return os.WriteFile(gi, append(data, []byte("\n"+entry+"\n")...), 0o644)
}

const indexHeader = `<!-- Auto-generated by ` + "`.starfleet-ai/bin/starfleetctl agents reindex`" + ` — do not hand-edit.
     Edit the fragment files themselves (.starfleet-ai/agents.d/<slug>.md) instead, then
     re-run reindex (agents new/write do this for you automatically). -->

`
