// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Enrico Weigelt, metux IT consult
//
// Package agents implements the modular fragment system: per-topic fragment
// files under agents.d/ and .starfleet-ai/var/agents.d/starfleet/, each a
// Markdown body with a small frontmatter block. The auto-generated index
// (.starfleet-ai/var/agents.d/index.md) and CLAUDE.md embed every
// fragment's body inline (frontmatter stripped). Only `reindex` (a pure
// function of the current fragment set) touches the generated files.
package agents

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Agents holds one invocation's resolved locations.
type Agents struct {
	Root   string // workspace root (toplevel of the git checkout)
	GitDir string // absolute .git dir, for the shared clone lock file
}

// New resolves an Agents rooted at the given workspace root.
func New(root string) (*Agents, error) {
	out, err := runCapture(root, "git", "rev-parse", "--absolute-git-dir")
	if err != nil {
		return nil, fmt.Errorf("agents: not inside a git working tree: %w", err)
	}
	return &Agents{
		Root:   root,
		GitDir: strings.TrimSpace(out),
	}, nil
}

func (a *Agents) branch() (string, error) {
	out, err := runCapture(a.Root, "git", "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(out), nil
}

// FragmentsDir returns the path to user-maintained fragments (agents.d/).
func (a *Agents) FragmentsDir() string {
	return filepath.Join(a.Root, "agents.d")
}

// StarfleetFragmentsDir returns the path to auto-rolled starfleet instruction
// fragments (.starfleet-ai/var/agents.d/starfleet-instructions/). These are
// tool-owned and gitignored.
func (a *Agents) StarfleetFragmentsDir() string {
	return filepath.Join(a.Root, ".starfleet-ai", "var", "agents.d", "starfleet-instructions")
}

// IndexFile returns the path to the auto-generated fragment index
// (.starfleet-ai/var/agents.d/index.md).
func (a *Agents) IndexFile() string {
	return filepath.Join(a.Root, ".starfleet-ai", "var", "agents.d", "index.md")
}

func (a *Agents) fragmentPath(slug string) string {
	// Starfleet-owned instruction fragments live under .starfleet-ai/var/agents.d/starfleet-instructions/
	if strings.HasPrefix(slug, "starfleet-instructions/") {
		return filepath.Join(a.Root, ".starfleet-ai", "var", "agents.d", slug+".md")
	}
	return filepath.Join(a.FragmentsDir(), slug+".md")
}

const indexHeader = `<!-- Auto-generated by ` + "`.starfleet-ai/bin/starfleetctl agents reindex`" + ` — do not hand-edit.
     Edit the fragment files themselves (.starfleet-ai/var/agents.d/<slug>.md) instead, then
     re-run reindex (agents new/write do this for you automatically). -->

`

const claudeHeader = `# CLAUDE.md

This file is auto-generated by ` + "`.starfleet-ai/bin/starfleetctl agents reindex`" + ` — do not
hand-edit. Edit the fragment files themselves (agents.d/<slug>.md) instead,
then re-run reindex. It contains every fragment's body inlined (frontmatter
stripped) so that agents which don't resolve @-imports (e.g. opencode) receive
the full instructions.

`
