// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Enrico Weigelt, metux IT consult
//
// Package sop implements the modular fragment system: per-topic fragment
// files under sop.d/ and .starfleet-ai/var/sop.d/starfleet/, each a
// Markdown body with a small frontmatter block. The auto-generated index
// (.starfleet-ai/var/sop.d/index.md) and CLAUDE.md embed every
// fragment's body inline (frontmatter stripped). Only `reindex` (a pure
// function of the current fragment set) touches the generated files.
package sop

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/metux/starfleetctl/internal/projectconfig"
)

// SOP holds one invocation's resolved locations.
type SOP struct {
	Root   string // workspace root (toplevel of the git checkout)
	GitDir string // absolute .git dir, for the shared clone lock file
	// fragmentsDir is the user-maintained fragments directory name, resolved
	// from project.yaml (fragments_dir) with "sop.d" as default.
	fragmentsDir string
}

// New resolves an SOP rooted at the given workspace root.
func New(root string) (*SOP, error) {
	out, err := runCapture(root, "git", "rev-parse", "--absolute-git-dir")
	if err != nil {
		return nil, fmt.Errorf("sop: not inside a git working tree: %w", err)
	}
	dir := "sop.d"
	if pc, lerr := projectconfig.Load(root); lerr == nil && pc.FragmentsDir != "" {
		dir = pc.FragmentsDir
	}
	return &SOP{
		Root:         root,
		GitDir:       strings.TrimSpace(out),
		fragmentsDir: dir,
	}, nil
}

func (s *SOP) branch() (string, error) {
	out, err := runCapture(s.Root, "git", "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(out), nil
}

// FragmentsDir returns the path to user-maintained fragments (sop.d/).
// Configurable via project.yaml: fragments_dir (default: "sop.d").
func (s *SOP) FragmentsDir() string {
	return filepath.Join(s.Root, s.fragmentsDir)
}

// StarfleetFragmentsDir returns the path to auto-rolled starfleet instruction
// fragments (.starfleet-ai/var/sop.d/starfleet-instructions/). These are
// tool-owned and gitignored.
func (s *SOP) StarfleetFragmentsDir() string {
	return filepath.Join(s.Root, ".starfleet-ai", "var", "sop.d", "starfleet-instructions")
}

// IndexFile returns the path to the auto-generated fragment index
// (.starfleet-ai/var/sop.d/index.md).
func (s *SOP) IndexFile() string {
	return filepath.Join(s.Root, ".starfleet-ai", "var", "sop.d", "index.md")
}

func (s *SOP) fragmentPath(slug string) string {
	// Starfleet-owned instruction fragments live under .starfleet-ai/var/sop.d/starfleet-instructions/
	if strings.HasPrefix(slug, "starfleet-instructions/") {
		return filepath.Join(s.Root, ".starfleet-ai", "var", "sop.d", slug+".md")
	}
	p := filepath.Join(s.FragmentsDir(), slug+".md")
	// Legacy fallback: existing fragments still live in the old agents.d/ dir.
	if _, err := os.Stat(p); err != nil {
		legacy := filepath.Join(s.Root, "agents.d", slug+".md")
		if _, lerr := os.Stat(legacy); lerr == nil {
			return legacy
		}
	}
	return p
}

const indexHeader = `<!-- Auto-generated by ` + "`.starfleet-ai/bin/starfleetctl sop reindex`" + ` — do not hand-edit.
     Edit the fragment files themselves (.starfleet-ai/var/sop.d/<slug>.md) instead, then
     re-run reindex (sop new/write do this for you automatically). -->

`

const claudeHeader = `# CLAUDE.md

This file is auto-generated by ` + "`.starfleet-ai/bin/starfleetctl sop reindex`" + ` — do not
hand-edit. Edit the fragment files themselves (sop.d/<slug>.md) instead,
then re-run reindex. It contains every fragment's body inlined (frontmatter
stripped) so that ships which don't resolve @-imports (e.g. opencode) receive
the full instructions.

`
